use_frameworks!

platform :ios, '8.0'

target 'ZZMakeFMDBManager_Example' do
  pod 'ZZMakeFMDBManager', :path => '../'

  target 'ZZMakeFMDBManager_Tests' do
    inherit! :search_paths

    
  end
end
